### ISSUE TITLE
Research and document Google Maps API

### ISSUE THREAD

**Issue by jobimathai1** [jobimathai1/project-1#7]

**Comment by jobimathai1** [comment]
Please add implementation documentation to this ticket.

**Comment by BTReyes** [comment]
https://developers.google.com/maps/documentation/javascript/adding-a-google-map

1- To use, billing must be enabled to obtain an API key
2- Hide API (per Jobi's slack link) https://gist.githubusercontent.com/derzorngottes/3b57edc1f996dddcab25/raw/f9c8ef6763de3743404c9c8314365bf9d1cf8880/Hide%2520API%2520Keys
3-

**Comment by BTReyes** [comment]
given to Rashid
